/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    get: operations["AppController_healthCheck"];
  };
  "/test": {
    get: operations["AppController_getTesting"];
  };
  "/auth/google/authenticate": {
    post: operations["AuthController_authenticateGoogleUser"];
  };
  "/auth/github/authenticate": {
    post: operations["AuthController_authenticateGithubUser"];
  };
  "/auth/password-less/send-email": {
    post: operations["AuthController_sendEmailForPasswordLess"];
  };
  "/auth/password-less/generate": {
    post: operations["AuthController_generatePasswordLessToken"];
  };
  "/auth/password-less/authenticate": {
    post: operations["AuthController_AuthenticatePasswordLessLogin"];
  };
  "/auth/access-token/generate": {
    post: operations["AuthController_generateAccessToken"];
  };
  "/auth/access-token/verify": {
    post: operations["AuthController_verifyAccessToken"];
  };
  "/generator/predict": {
    get: operations["GeneratorController_predict"];
  };
  "/generator/predict/{documentId}/scribble": {
    post: operations["GeneratorController_scribblePredict"];
  };
  "/generator/predict/{documentId}/caption": {
    post: operations["GeneratorController_CaptionPredict"];
  };
  "/documents": {
    get: operations["DocumentController_getList"];
    post: operations["DocumentController_saveDocument"];
  };
  "/documents/{id}": {
    get: operations["DocumentController_getOne"];
    delete: operations["DocumentController_deleteDocument"];
    patch: operations["DocumentController_updateDocument"];
  };
  "/documents/{id}/image": {
    get: operations["DocumentController_getImage"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AuthenticateGithubUserDto: {
      code: string;
    };
    AuthenticateResponse: {
      /** @default true */
      success: boolean;
      /** Format: date-time */
      expiresAtUtc: string;
      accessToken: string;
      isFirstTime: boolean;
    };
    ErrorResponse: {
      statusCode: number;
      message: string[];
    };
    SendEmailForPasswordLessDto: {
      email: string;
    };
    AddOneTimeTokenDto: {
      username: string | null;
      email: string;
    };
    VerifyTokenDto: {
      token: string;
    };
    GenerateTokenDto: {
      userId: number;
    };
    VerifyTokenResponse: {
      userId: string;
      username: string;
      email: string | null;
      imageUrl: string | null;
    };
    PredictResponse: {
      urls: string[];
    };
    ScribblePredictBody: {
      prompt: string;
    };
    DocumentRecord: {
      id: string;
      title: string;
      description: string | null;
      svg: string | null;
      image: string | null;
      paths: Record<string, unknown> | null;
    };
    GetDocumentListResponse: {
      records: components["schemas"]["DocumentRecord"][];
    };
    DocumentDetailRecord: {
      id: string;
      title: string;
      description: string | null;
      svg: string | null;
      image: string | null;
      paths: Record<string, unknown> | null;
    };
    GetDocumentResponse: {
      record: components["schemas"]["DocumentDetailRecord"];
    };
    SaveDocumentResponse: {
      id: string;
    };
    SaveDocumentDto: {
      title: string;
      description: string | null;
      svg: string | null;
      image: string | null;
      paths: Record<string, unknown> | null;
    };
    UpdateDocumentDto: {
      id: string;
      data: components["schemas"]["SaveDocumentDto"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  AppController_healthCheck: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AppController_getTesting: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_authenticateGoogleUser: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthenticateGithubUserDto"];
      };
    };
    responses: {
      /** @description Authenticate with Google */
      201: {
        content: {
          "application/json": components["schemas"]["AuthenticateResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot authenticate with Google */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  AuthController_authenticateGithubUser: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthenticateGithubUserDto"];
      };
    };
    responses: {
      /** @description Authenticate with Github */
      201: {
        content: {
          "application/json": components["schemas"]["AuthenticateResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot authenticate with Github */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  AuthController_sendEmailForPasswordLess: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendEmailForPasswordLessDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_generatePasswordLessToken: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddOneTimeTokenDto"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  AuthController_AuthenticatePasswordLessLogin: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyTokenDto"];
      };
    };
    responses: {
      /** @description Authenticate with Email */
      201: {
        content: {
          "application/json": components["schemas"]["AuthenticateResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Cannot authenticate with Email */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  AuthController_generateAccessToken: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateTokenDto"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  AuthController_verifyAccessToken: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyTokenDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["VerifyTokenResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  GeneratorController_predict: {
    parameters: {
      query: {
        prompt: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PredictResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  GeneratorController_scribblePredict: {
    parameters: {
      path: {
        documentId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScribblePredictBody"];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  GeneratorController_CaptionPredict: {
    parameters: {
      path: {
        documentId: string;
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
  DocumentController_getList: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetDocumentListResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  DocumentController_saveDocument: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveDocumentDto"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["SaveDocumentResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  DocumentController_getOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GetDocumentResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  DocumentController_deleteDocument: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DocumentController_updateDocument: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateDocumentDto"];
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  DocumentController_getImage: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["SaveDocumentResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
